added checks for gperf, erroring out if not found

diff --git a/src/hash/generate_headers b/src/hash/generate_headers
--- a/src/hash/generate_headers
+++ b/src/hash/generate_headers
@@ -1,5 +1,14 @@
 #!/bin/sh
 
+# Check for gperf
+if `type gperf > /dev/null 2> /dev/null`
+then
+  echo "Found gperf, making headers..."
+else
+  echo "gperf not found, aborting" >&2
+  exit 1
+fi
+
 gperf -L ANSI-C -E -D -K key -H ohcount_hash_language -N ohcount_hash_language_from_name -t languages.gperf > language_hash.c
 gperf -L ANSI-C -E -D -K key -H ohcount_hash_extension -N ohcount_hash_language_from_ext -t extensions.gperf > extension_hash.h
 gperf -L ANSI-C -E -D -K key -H ohcount_hash_filename -N ohcount_hash_language_from_filename -t filenames.gperf > filename_hash.h
